meta:
    engine: 4.1.0
    version: 0.0.2
    author: danikong

units:
    kx: u
    ky: u
    px: u + 2
    py: u + 2
    kcow: 14
    kcoh: 14
    pad: 2

    spacing: 0.75

    controllerW: 18.5
    controllerH: 33.5
    belowControllerH: 17
    caseBorder: 1.5
    screwThreadRadius: 0.5
    screwPCBRadius: 4.0

points:
    key.padding: cy
    zones:
        main:
            anchor:
                # Shift the PCB slightly to the right and down, otherwise it's weirdly positioned outside of the main sheet in KiCad
                shift: [100, -150]
            rows:
                bottom.row_net: P6
                home.row_net: P7
                top.row_net: P8
                num.row_net: P9
            columns:
                outer:
                    key:
                        col_net: P3
                        spread: cx
                        splay: 8
                    rows:
                        bottom:
                            row_net: P16
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_outer_home
                        home:
                            row_net: P6
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky_home
                        top:
                            row_net: P7
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_outer_num
                        num:
                            row_net: P8
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky_num
                pinky:
                    key:
                        col_net: P4
                        spread: cx
                    rows:
                        bottom:
                            row_net: P16
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_outer_bottom
                        home:
                            row_net: P6
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_bottom
                        top:
                            row_net: P7
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_outer_top
                        num:
                            row_net: P8
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_top
                ring:
                    key:
                        col_net: P5
                        stagger: cy-1
                        spread: cx+1
                        splay: -8
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_middle_bottom
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky_top
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_middle_top
                        num:
                            led_in: "rgb_{{name}}"
                middle:
                    key:
                        col_net: P18
                        stagger: 2
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_index_bottom
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_home
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_index_top
                        num:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_num
                index:
                    key:
                        col_net: P15
                        stagger: -2
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_inner_bottom
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_middle_home
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_inner_top
                        num:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_middle_num
                inner:
                    key:
                        col_net: P14
                        stagger: -2
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_inner_home
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_index_home
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_inner_num
                        num:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_index_num
        thumb:
            anchor:
                ref: main_inner_bottom
                shift: [-0.6cx, -cy]
            rows.home.row_net: P16
            columns:
                outer.key:
                    col_net: P18
                    led_in: "rgb_{{name}}"
                    led_out: rgb_main_pinky_bottom
                    spread: cx
                home.key:
                    col_net: P15
                    led_in: "rgb_{{name}}"
                    led_out: rgb_thumb_outer_home
                    spread: cx + 2
                    rotate: -18
                    stagger: -3.2
                inner.key:
                    col_net: P14
                    led_in: P19
                    led_out: rgb_thumb_home_home
                    spread: cx
                    rotate: -36
                    stagger: -9.2
outlines:   
    _base:
        - what: rectangle
          bound: true
          where:
              - /main/
              - /thumb/
          size: [cx, cy]
    _board_outline:
        - what: polygon
          fillet: 2
          points:
              - ref: thumb_inner_home
                shift: [0.6cx, 0.6cy]
              - ref: thumb_inner_home
                shift: [0.6cx, -0.6cy]
              - ref: thumb_inner_home
                shift: [-0.4cx, -0.6cy]

              - ref: thumb_home_home
                shift: [0.4cx, -0.6cy]
              - ref: thumb_home_home
                shift: [-0.4cx, -0.6cy]

              - ref: thumb_outer_home
                shift: [0.4cx, -0.6cy]
              - ref: thumb_outer_home
                shift: [-0.6cx, -0.6cy]

              - ref: main_middle_bottom
                shift: [0.5cx, -1.5cy]
              - ref: main_middle_bottom
                shift: [-1cx, -1.5cy]

              - ref: main_outer_bottom
                shift: [1.6cx, -0.6cy]
              - ref: main_outer_bottom
                shift: [0.6cx, -0.6cy]
              - ref: main_outer_bottom
                shift: [-0.6cx, -0.6cy]

              - ref: main_outer_num
                shift: [-0.6cx, 0.6cy]
              - ref: main_outer_num
                shift: [0.5cx, 0.6cy]

              - ref: main_ring_num
                shift: [-0.5cx, 0.6cy]
              - ref: main_ring_num
                shift: [0.4cx, 0.6cy]

              - ref: main_middle_num
                shift: [-0.4cx, 0.61cy]
              - ref: main_middle_num
                shift: [0.4cx, 0.6cy]

              - ref: main_index_num
                shift: [-0.4cx, 0.6cy]
              - ref: main_index_num
                shift: [0.5cx, 0.6cy]

              - ref: main_inner_num
                shift: [-0.4cx, 0.6cy]
              - ref: main_inner_num
                shift: [0.5cx, 0.6cy]

              - ref: main_inner_num
                shift: [0.6cx, 0.4cy]
              - ref: main_inner_num
                shift: [2cx, 0.4cy]
              - ref: main_inner_num
                shift: [2cx, -4cy]

              - ref: thumb_inner_home
                shift: [0.16cx, 0.65cy]
    _keycap_outlines:
        - what: rectangle
          fillet: 2
          where: true
          size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
    preview:
        - what: outline
          name: _board_outline
          operation: stack
        - what: outline
          name: _keycap_outlines
          operation: stack
    _switch_cutouts:
        - what: rectangle
          where:
              - /main/
              - /thumb/
          size: [kcow, kcoh]
    _board_plate:
        - what: outline
          name: _base
        - what: polygon
          operation: add
          points:
              - ref: main_index_bottom
                shift: [-0.5 cx, 0]
              - ref: thumb_inner_home
                shift: [-0.5 cx, -0.5 cy]
              - ref: thumb_home_home
                shift: [0.5 cx, -0.5 cy]
              - ref: thumb_inner_home
                shift: [0.5 cx, -0.5 cy]
              - ref: thumb_inner_home
                shift: [0.5 cx, 0.5 cy]
              - ref: thumb_home_home
                shift: [0.5 cx, 0.55 cy]
              - ref: main_inner_bottom
                shift: [0.5 cx, 0]
        - what: polygon
          operation: add
          points:
              - ref: main_index_bottom
                shift: [0.5 cx, -0.5 cy]
              - ref: main_ring_bottom
                shift: [-0.5 cx, -0.5 cy]
              - ref: main_index_bottom
                shift: [0.5 cx, 0.5 cy]
              - ref: main_ring_bottom
                shift: [0.5 cx, 0.5 cy]
        - what: outline
          name: _board_plate
          expand: 2
        - what: outline
          name: _switch_cutouts
          operation: subtract
    plate:
        - what: outline
          name: _board_plate
cases.speedy-o:
    - what: outline
      name: _board_outline
      extrude: 3
      operation: subtract
    - what: outline
      name: _keycap_outlines
      extrude: 6
      operation: add
pcbs:
    plate:
        template: kicad8 # Required, since footprints are KiCad 8 only
        outlines:
            main.outline: plate
        footprints:
            front_text: &text
                what: text
                where: &textWhere
                    ref:
                        - main_index_bottom
                    shift: [-0.4cx, 0.5 cy]
                params: &textParams
                    text: Choc Switch Plate
                    justify: left
            back_text:
                <<: *text
                where:
                    <<: *textWhere
                    shift: [0.4cx, 0.5 cy]
                params:
                    <<: *textParams
                    layer: B.SilkS
                    justify: left mirror
            left_text: &text
                what: text
                where: &textWhere
                    ref:
                        - main_inner_bottom
                    shift: [-0.1cx, 0.5 cy]
                params: &textParams
                    layer: F.SilkS
                    text: Left
                    justify: left
            right_text: &text
                what: text
                where: &textWhere
                    ref:
                        - main_inner_bottom
                    shift: [0.1cx, 0.5 cy]
                params: &textParams
                    text: Right
                    layer: B.SilkS
                    justify: left mirror
    speedy-o:
        template: kicad8 # Required, since footprints are KiCad 8 only
        outlines:
            main.outline: _board_outline
            keycaps_front:
                outline: _keycap_outlines
                layer: F.SilkS
            keycaps_back:
                outline: _keycap_outlines
                layer: B.SilkS
        footprints:
            led:
                what: led_sk6812mini-e
                where: true
                adjust:
                    shift: [0, 4.7]
                params:
                    P2: "{{led_in}}"
                    P4: "{{led_out}}"
                    reversible: true
            diode_index_inner:
                what: sod-123w
                where: /^main_(?:index|inner)_\w*$/
                params:
                    from: "{{name}}"
                    to: "{{row_net}}"
                adjust:
                    shift: [-8, 2.2]
                    rotate: 270
            diode_other_main:
                what: sod-123w
                where: /^main_(?:outer|pinky|ring|middle)_\w*$/
                params:
                    from: "{{name}}"
                    to: "{{row_net}}"
                adjust:
                    shift: [-8, 0.6]
                    rotate: 270
            diode_thumb:
                what: sod-123w
                where: /^thumb_(?:outer|home|inner)_home$/
                params:
                    from: "{{name}}"
                    to: "{{row_net}}"
                adjust:
                    shift: [-8, 0.6]
                    rotate: 270
            choc:
                what: choc
                where: true
                adjust:
                    rotate: 180
                params:
                    keycaps: true
                    reverse: true
                    hotswap: true
                    from: "{{col_net}}"
                    to: "{{name}}"
            promicro_pretty:
                what: promicro_pretty
                where:
                    ref: main_inner_top
                adjust:
                    shift: [25, 7]
                params:
                    reversable_pins:
                        13
                        # rotate: -90
            battery_front:
                what: jstph
                where:
                    ref: main_inner_top
                    shift: [0.7cx, -0.3cy]
                    rotate: 0
                params:
                    side: F
                    pos: pos
                    neg: GND
            battery_back:
                what: jstph
                where:
                    ref: main_inner_top
                    shift: [0.7cx, -0.3cy]
                    rotate: 0
                params:
                    side: B
                    pos: pos
                    neg: GND
            on-off-switch:
                what: pcm12
                where:
                    ref: main_inner_bottom
                    shift: [33.6, 0.2cy]
                    rotate: 90
                params:
                    from: pos
                    to: RAW
            reset_front:
                what: button
                params:
                    side: F
                    from: GND
                    to: RST
                where:
                    ref.aggregate.parts: [main_inner_bottom]
                    shift: [1.7cx, -0.6cy]
                    rotate: -90
            reset_back:
                what: button
                params:
                    side: B
                    from: GND
                    to: RST
                where:
                    ref.aggregate.parts: [main_inner_bottom]
                    shift: [1.7cx, -0.6cy]
                    rotate: -90
            trrs:
                what: trrs_tight
                where:
                    ref: main_inner_home
                    shift: [35.5, -0.4cy]
                    rotate: -90
                params:
                    reverse: true
                    symmetric: true
                    # The naming of the nets on this footprint is different from the Corne schematics.
                    A: ""
                    B: VCC
                    C: GND
                    D: P10
            hole_top_left:
                what: mounting_hole_plated
                where:
                    ref: main_ring_num
                    shift: [-0.8cx, 0]
            hole_bottom_left:
                what: mounting_hole_plated
                where:
                    ref: main_ring_bottom
                    shift: [0, -1cy]
            hole_bottom_middle:
                what: mounting_hole_plated
                where:
                    ref: main_index_bottom
                    shift: [-0.5cx, -1cy]
            hole_bottom_right:
                what: mounting_hole_plated
                where:
                    ref: thumb_home_home
                    shift: [0.4cx, 0.8cy]
            hole_top_right:
                what: mounting_hole_plated
                where:
                    ref: main_inner_num
                    shift: [0.7cx, 0]
            front_text: &text
                what: text
                where: &textWhere
                    ref: main_pinky_num
                    shift: [0, 0.6cy]
                params: &textParams
                    text: Speedy-O\nv0.1.0
                    justify: left
            back_text:
                <<: *text
                where:
                    <<: *textWhere
                    shift: [0.4cx, 0.6cy]
                params:
                    <<: *textParams
                    layer: B.SilkS
                    justify: left mirror
output:
  zmk:
    keymap: true